### ISSUE TITLE
Wrong version number in version 1.1.1

### ISSUE THREAD

**Issue by ManuelHu** [BxCppDev/bxdecay0#31]
The latest version 1.1.1 still has `1.1.0` in its cmake file: https://github.com/BxCppDev/bxdecay0/blob/1.1.1/CMakeLists.txt#L14

This makes it hard to determine if we can enable Geant4's MT runmode with BxDecay0 in remage. It would be nice to have a release that has the correct version in `CMakeLists.txt` _and_ can be downloaded from the correct git tag. So either:
* a re-created tag for 1.1.1 that has the correct version set
* or a new release 1.1.2, if you do not want to change old git tags.

Thanks!

**Comment by gipert** [comment]
@fmauger could you merge this and release a new version? More in general, are you still maintaining this repository? Are there plans for the future?

**Comment by fmauger** [comment]
Hi both, 
Thanks for noticing this issue. Fixed in new release 1.1.2.
For now, there is no new dev plans (needs for new particle generator) in my particle/nuclear physics community. But this can quickly change. Of course I'll continue to maintain this piece of software for it is very important for the simulation of our experiment. As we are starting the data taking and soon should enter some massive MC production, I guess that we will need some debugging phase because some of the provided generators have not been tested intensively yet. However, do not hesitate to propose/ask for new stuff and I'll consider it.
In principle I'd like to write a (NIM-A) paper about this library but I systematically lack of time for this task !!!
Best

**Comment by gipert** [comment]
Thanks @fmauger :) LEGEND would like to use BxDecay0 in the long term for its simulations too, so it's good to know that it will be maintained. For what concerns us, BxDecay0 already offers all the features we need!
