### ISSUE TITLE
Using DECAY9 for background simulation of DUNE

### ISSUE THREAD

**Issue by HanFangXie** [BxCppDev/bxdecay0#5]
I found that the DEAY0 is very useful and would like to use it on background simulation for DUNE. Do you feel okay with it? Is there any requirement about the copyright?
Also, I have a few questions.
Will DECAY0 be long-term supported for several years?
Is it possible to add some other decays? If yes, how hard would that be? Can we contribute to this?

**Comment by fmauger** [comment]
Hi HanFangXie,

Of course you are welcome to use the BxDecay0 library for Dune's sims. The licence is the GNU General Public License v3.0 so that you/Dune collab must publish derived work from BxDecay0 as a compatible open source licence. 

The original decay0 fortran program is maintained by Vladimir Tretyak and usually available from the following URL: 
https://www.dropbox.com/sh/nky7k414bqevhv7/AACnr_ncW5mJdY7huq9EaxcCa?dl=0

The BxDecay0  lib is maintained by me and I plain to continue for years (at least 5 !) . Anyway, anyone is invited to fork the project and maintained its own version. However, it would be probably more useful to keep synchronized with the original version because I'm in touch with Vladimir to keep in sync with the original fortran version.

It is in principle possible to add more decays. However in such case, I do not follow Vladimir coding scheme (fortran based) but a reasonable OOP approach with dedicated classes for particles' kinematics and "primary" events. We are currently in the process to add some additional DBD decay modes using some tabulated phase space factors provided by theoreticians. For that we use pure C++ programming without using the C++ primitives adapted from the original fortran code. The idea is to benefit of the port of the original fortran code but also to be able to extend the library with new generators implemented in C++ without counterpart in the original Decay0 program. 

Each add-on generator  must be statically managed. There is no support for dynamic plugin with external generators. If you need such a feature, it is better to use the Bayeux library with its embedded genbb module (which is in fact the first version of the C++ port of decay0). The future version of Bayeux will use BxDecay0 in place of its embedded decay0 port (soon deprecated). Within the SuperNEMO DBD experiment, we use Bayeux to implement various decay generators of interest: not only the generators provided by the Decay0 C++ port, but also arbitrary additional ones provided by Bayeux itself or by client software through a plugin mechanism. Bayeux also provides some interfaces to generate standalone decay files in a simple text format or various formats based on Boost/Serialization. it's up to you to think about the best technique/lib to use.
If you and the DUNE's software group want to discuss further on the better choice for your project, feel free to contact me by email directly.

Hope it helps.
Cheers
frc

**Comment by fmauger** [comment]
Version 1.0.4 seems to be suitable for DUNE to start with.
