### ISSUE TITLE
U238 decay chain

### ISSUE THREAD

**Issue by plasorak** [BxCppDev/bxdecay0#9]
Hello,
I was looking for the U238 decay chain in the code but I cannot find it, [this ref](https://arxiv.org/pdf/nucl-ex/0104018.pdf) seems to be showing on Fig 1 all the particles output, but when I try to generate U238 or Rn222 background decays, the code throws an error.
Maybe this hasn't been ported yet?
Thanks
Pierre

**Comment by plasorak** [comment]
By the way, with the correct data, it doesn't look to be too complicated for me to implement it, so if that data is somewhere in hand, I'm happy to do it and go through the usual pull request process.

**Comment by fmauger** [comment]
Hi Pierre,

You are right, the current version of BxDecay0, as a port of decay0 release "2020-04-20" (with a few additional features), does not contain the decay schemes for (here for the U238 chain):

- U238
- U234
- Th230
- Rn222
- Po218
- Po210

Note: Po214 is included as a cascade in Bi214 decay.

My guess is that the legacy decay0 has concentrated mostly on beta emitters because they are usually the more dangerous background providers for double beta decay experiments.
However, Vladimir may have some variant of his Fortran code that contains such decay models (or part of them) with alpha emitters (useful for dark matter/HPGe and other crystal based experiments with surface contamination issues).
Let me ask him before to go further and then we will see what can be done.

**Comment by fmauger** [comment]
Note that the reference you gave reflects the features in the decay4 program (not decay0). decay4 is likely a variant of decay0 and probably implement functionalities that are a little different from decay0. Vladimir will say more about it.

**Comment by fmauger** [comment]
Note also that Rn222 would be useful too for educational simulation project (alpha spectrometry lab...)

**Comment by plasorak** [comment]
I see, thanks. I hadn't noticed the difference.

**Comment by fmauger** [comment]
I have no access to the original decay4 code too and I don't know if it is still maintained by Vladimir. So let's wait and see. I sent a message to him.

**Comment by fmauger** [comment]
Excerpt from Vlad's answer:

> By the way, one of reasons why I did not create independent subroutines for specific alpha
> decayers, is that many of them decay mainly to the
> ground daughter state (e.g. 99.92% for 222-Rn). So, their decays can be
> easily generated with the so called "artificial event" in Decay0, when one
> can construct artificial decay consisting of up to 10 parts, and each part
> can be alpha or beta particle or pions, etc. So, for 99.92% of 222-Rn one
> can use "art. event" consisting of 1 part, and this part is emission of
> alpha particle with E=5.590/222*218=5.489 MeV.

The point is that BxDecay0 does not port the  "artificial event" from Decay0 because
originally the Bayeux library has its own "universal single particle generator" so I had 
no need for this kind of stuff so far and also because the alpha emitters are of no interest for the SuperNEMO usecase.

However, Vladimir is ok to provide in decay0  the missing alpha decayers you will ask.
In the meanwhile, we/you can implement very simplified version of them (only dominant alpha decays) in BxDecay0.
I think this approach is rather good for it would make the BxDecay0 interface more uniform and complete and also users won't have to know the details of all the decay schemes (Q-values, branching ratios...) associated to these isotopes.
This work could be also updated by expert people like Vladimir to take into account fine effects like internal conversion...

**Comment by fmauger** [comment]
As an exercise, I have added a simple Rn222 alpha generator with support for ground (0+) and 513 keV (2+) levels of Po218 (NDC: https://www.nndc.bnl.gov/nudat2/chartNuc.jsp).

New files are: 
- bxdecay0/Rn222.h
- bxdecay0/Rn222.cc

Modified files:
- bxdecay0/genbbsub.cc (search for "Rn222" string)
- CMakeLists.txt

**Comment by plasorak** [comment]
Hi,
I see, that doesn't look terribly complicated.
The thing that does look complicated and error prone is parsing the NNDC website :s

I'll give it a go for the next decays.

**Comment by fmauger** [comment]
Hmmm, nuclear data tables are not famous for their clarity and accessibility for modern software interface.
